---
onet:
    s3_path: 'onet-bucket/prefix'
    cache_dir: 'onet_cache'
job_postings:
    s3_path: 'jobs-bucket/converted'
labeled_postings:
    s3_path: 'postings-bucket/labeled'
output_tables:
    s3_path: 'output-bucket/tables'
local_mode: True
output_folder: 'output'
...
