---
onet:
    s3_path: 'onet-bucket/prefix'
    cache_dir: 'onet_cache'
job_postings:
    s3_path: 'jobs-bucket/converted'
labeled_postings:
    s3_path: 'postings-bucket/labeled'
output_tables:
    s3_path: 'output-bucket/tables'
    geo_title_count_dir: 'geo_title_count'
    title_count_dir: 'title_count'
    cleaned_geo_title_count_dir: 'cleaned_geo_title_count'
    cleaned_title_count_dir: 'cleaned_title_count'
    geo_soc_common_count_dir: 'geo_soc_common_count'
    soc_common_count_dir: 'soc_common_count'
    geo_soc_top_count_dir: 'geo_soc_top_count'
    soc_top_count_dir: 'soc_top_count'
    geo_soc_given_count_dir: 'geo_soc_given_count'
    soc_given_count_dir: 'soc_given_count'
local_mode: True
output_folder: 'output'
partner_stats:
    s3_path: 'stats-bucket/partner-etl'
raw_jobs_s3_paths:
    XX: 'some-bucket/jobs/dump/'
airflow_contacts:
    - datascifellows@gmail.com
...
